### PR TITLE
CODE OF CONDUCT AND CONTRIBUTING.MD ADDED

### PR DESCRIPTION
**Pull request by smriti1313**
code of conduct and contributing.md added. Contributing.md basically has instructions one can  use if they are contributing for the first time in open source.

issue #9 has been resolved.

### CODE REVIEW

**Review by ssg8288 — APPROVED** [review]
Code of Conduct seems to be much important documentation which was lacking in this repository @smriti1313, thanks for your contribution and time this is great

**Review by ssg8288 — APPROVED** [review]
thanks again, it was wonderful, You have some good documentation skills I must say @smriti1313

**Comment by smriti1313** [comment]
> 
> 
> thanks again, it was wonderful, You have some good documentation skills I must say @smriti1313


Thank you for giving me  a chance. 
closed #9

**Review by ssg8288 — COMMENTED** [review]
reviewed the changes made

**Pull request merged**
