### PR TITLE
Code and documentation updated

### LINKED ISSUE #2: CODE FOR GPS OR GSM VEHICLE TRACKING FOR ARDUINO
@DWOC2020 @DWOC

- [ ] code for GPS on arduino

### PR DESCRIPTION
**Pull request by Pranjal-2001**

### CODE REVIEW

**Review by ssg8288 — APPROVED** [review]
cool 👍🏻

**Comment by ssg8288** [comment]
issues #6  #2 solved

**Comment by Zircoz** [comment]
Use 1 label for level only

**Comment by ssg8288** [comment]
> 
> 
> Use 1 label for level only

FYI he submitted this PR for two issues having different labels which you can verify under the closed issues ...thus, I had to close the pull request all together with the issues linked #6 and #2. Thank you

**Comment by Zircoz** [comment]
@ssg8288 not saying that his work is invalid but DWOC's backend will only pickup one of the level label imo. (though ask them if my intuition is right, and if it is just ask him to do another PR only for representation and assign one of the level labels to it)

**Comment by ssg8288** [comment]
> 
> 
> @ssg8288 not saying that his work is invalid but DWOC's backend will only pickup one of the level label imo. (though ask them if my intuition is right, and if it is just ask him to do another PR only for representation and assign one of the level labels to it)

@Zircoz well well this will be a tedious task for him then lmfao XD....I got you what you are tryna say it hit me too while I was merging the request but I thought since, I linked two issues separately then it should not effect much 
well I will first get it confirmed from the core team then will ask him if this needs to be sorted thanks for pointing it out.

**Comment by Zircoz** [comment]
Issues are not checked by backend, labels on issues are just to make it more descriptive for contributors.
@ssg8288

**Comment by ssg8288** [comment]
@Pranjal-2001  this msg is in regards for your recent commit and PR since you merged the code and documentation altogether i linked the issues and level tags in the same pull requests but this will be a issue for you on calculating your points
thus i  would ask you to just create another pull request for either the code or document by adding a  small change or comments and pull a request which will be merged against of the issue which will lead to your points then hope you understand

**Comment by Pranjal-2001** [comment]
Okay code is level 5 so we will let it be like that. I will make a few
changes in documentation.

**Pull request merged**
