### PR TITLE
README BADGES / SHIELDS ADDED FEATURE 

### PR DESCRIPTION
**Pull request by akrish4**
I have added the badges in readme now and it look awesome now.
Kindly merge it.

nice1

Kindly add the same labels to PR also

### CODE REVIEW

**Review by ssg8288 — COMMENTED** [review]
[Issues](https://github.com/ssg8288/Surviellance-Bomb-Diffusion-Robot/issues)
it seems that this line has some issues while you were copying it it says harsh-9in check it

**Comment by akrish4** [comment]
> [Issues](https://github.com/ssg8288/Surviellance-Bomb-Diffusion-Robot/issues)
> it seems that this line has some issues while you were copying it it says harsh-9in check it

It is now resolved 
 Actually I have contributed the same thing to harsh-9in repository aswell , so it happened will editing ;)

**Comment by ssg8288** [comment]
> 
> 
> > [Issues](https://github.com/ssg8288/Surviellance-Bomb-Diffusion-Robot/issues)
> > it seems that this line has some issues while you were copying it it says harsh-9in check it
> 
> It is now resolved
> Actually I have contributed the same thing to harsh-9in repository aswell , so it happened will editing ;)

let me check and review it

**Comment by akrish4** [comment]
> > > [Issues](https://github.com/ssg8288/Surviellance-Bomb-Diffusion-Robot/issues)
> > > it seems that this line has some issues while you were copying it it says harsh-9in check it
> > 
> > 
> > It is now resolved
> > Actually I have contributed the same thing to harsh-9in repository aswell , so it happened will editing ;)
> 
> let me check and review it

yeah sure

**Review by ssg8288 — APPROVED** [review]
now its fine

**Pull request merged**
